# Generated by Django 4.2.1 on 2023-05-10 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfService',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', null=True, verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified', null=True, verbose_name='modified at')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Type of services',
                'db_table': 'type_of_services',
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', null=True, verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified', null=True, verbose_name='modified at')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('type_of_service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='infrastructure.typeofservice')),
            ],
            options={
                'verbose_name_plural': 'Packages',
                'db_table': 'packages',
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deliverables',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', null=True, verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified', null=True, verbose_name='modified at')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('packageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='infrastructure.package')),
            ],
            options={
                'verbose_name_plural': 'Deliverables',
                'db_table': 'deliverables',
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
